name: "Audit Rust Dependencies"
permissions:
  contents: read
on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: audit
  cancel-in-progress: true

jobs:
  audit:
    name: Audit Rust Deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # to open issues for unsafe dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          persist-credentials: false
      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # 1.2.7
